### ISSUE TITLE
Architectural design 

### ISSUE THREAD

**Issue by jf-garciam1** [ISIS3510-202410-Team5/Wiki#10]
Architectural design (AD), You should provide a complete architecture design that shows us the Architecture design, architecture, and design patterns and tactics that you are going to use. To show these architecture design choices use as many diagrams as needed. Remember that all the artifacts should have a rationale that helps the reader understand the diagram. A diagram without rationale will not be valid. (This is evaluated in the Wiki)

**Comment by samuelfreire03** [comment]
Everything was described in the wiki of the project, where it is justified with the model and its due justification.
