### ISSUE TITLE
Business Questions Sprint 2

### ISSUE THREAD

**Issue by jf-garciam1** [ISIS3510-202410-Team5/Wiki#8]
Business questions (BQs). List all the business questions that you will implement, in this sprint, with their respective type (and rationale if necessary). The implemented BQ should be part of the list you made for the Sprint 1 deliverable. (This is evaluated in the Wiki). Remember it is mandatory that the BQs must be implemented in the analytics system.

**Comment by samuelfreire03** [comment]
The person in charge developed all the code that allows to answer this question
